### ISSUE TITLE
About GPU usage

### ISSUE THREAD

**Issue by Ecalpal** [nianticlabs/monodepth2#185]
Your job is great！

When I ran the code for training, I found that the CPU usage was particularly high(100%), while the GPU usage was low(60%-70%). My CPU is i9-9900k, and I put the data on an nvme SSD.

Is GPU usage low due to data preprocessing, such as data enhancement? Is there any suggestion to solve this bottleneck problem?

**Comment by mrharicot** [comment]
Hi,
Ah that's interesting! I used to train monodepth2 with high 90% GPU usage on Titan Xp.
My guess is that since monodepth2 was written the GPUs got much faster while the CPUs only got a modest speed bump.
My best recommendation would be to modify the original KITTI conversion script to resize the images to the exact size you need, say 192x640, to avoid having to load and jpeg decode then resize a large image every time.

**Comment by Ecalpal** [comment]
I converted the resolution of all the pictures to 640 * 192. It didn't seem to work. The CPU utilization was maintained at 96% - 98%, at least a little better than 100%. GPU usage remains at 60% - 70%.

Then I set the batch_ size and num_ workers to 16, which also can't improve GPU usage (CPU is the bottleneck, but its task is heavier now).

Then I set the batch_ size and num_ workers to 4, CPU usage drops to 90%, GPU usage unchanged.

Parameter pin_ memory in dataloader is not the reason either.


Finally, I printed the time spent in each process of an iteration, which I divided into four parts: 
loading data,
https://github.com/nianticlabs/monodepth2/blob/d1c5f03c38305cae4e68917e472d2f9d4eda0b98/trainer.py#L201
forward propagation,
https://github.com/nianticlabs/monodepth2/blob/d1c5f03c38305cae4e68917e472d2f9d4eda0b98/trainer.py#L205
backward propagation
https://github.com/nianticlabs/monodepth2/blob/d1c5f03c38305cae4e68917e472d2f9d4eda0b98/trainer.py#L207
and logging.


Loading data and logging takes a short time, forward propagation requires 0.4s - 0.5s , back propagation needs 0.3s 。 It doesn't make sense that forward propagation takes more time than backward propagation.

In forward propagation, it takes about 0.02s to calculate depth, 0.08s to calculate attitude, 0.005s to predict image, and 0.3s to calculate loss function.

It seems that the loss function of self-supervised takes too much time, which is different from the supervised learning.

**Comment by mrharicot** [comment]
It is expected that the self-supervised loss will be more computationally expensive than a standard regression loss, however it is all happening on the GPU so there is no clear and immediate reason for the high CPU usage and low GPU usage.

Are you using pillow-simd?

**Comment by Ecalpal** [comment]
No, I didn't make any changes to your pipline.

Another interesting problem I found yesterday was that when I load the pre training model on the command line,
`python train.py --load_weight_folder=./models/mono_640x192 --models_to_load encoder depth pose_encoder pose --num_workers=12 --batch_size=12`
 a batch size of 12 resulted in out of memory and I had to change it to 8.

**Comment by mrharicot** [comment]
To ensure fast image preprocessing I recommend to install pillow-simd in case that isn't already the case (you will need to uninstall pillow first).
https://pypi.org/project/Pillow-SIMD/

A batch size of 12 might run out of memory if the GPU is already used to run an Xserver for instance.

**Comment by Rashfu** [comment]
> It is expected that the self-supervised loss will be more computationally expensive than a standard regression loss, however it is all happening on the GPU so there is no clear and immediate reason for the high CPU usage and low GPU usage.
> 
> Are you using pillow-simd?
Hi, @mrharicot @Ecalpal :
The question also happens on my computer with high CPU usage and low GPU usage.
Loss calculation [here](https://github.com/nianticlabs/monodepth2/blob/master/trainer.py#L258) takes about 0.3-0.5s per batch in RTX3090, while the dataloader usually takes less than 0.01s on CPU(But sometime up to 0.2s to load a batch).
But it turns out that CPU usage is high and GPU usage is low which doesn't match my test time.
